### ISSUE TITLE
padding/margin issue on login window on linux

### ISSUE THREAD

**Issue by sam0x17** [yue/wey#17] opened 2018-04-09 22:19 UTC
![screenshot from 2018-04-09 18-18-52](https://user-images.githubusercontent.com/1855021/38525996-8172a352-3c22-11e8-9c2e-69e6d55597e4.png)

Using Ubuntu 17.10, gnome skin = arc-dark

**Comment by zcbenz** [comment] 2018-04-10 08:48
This is a duplicate of #8.

**Closed by zcbenz** 2018-04-10 08:48 UTC
